spring:
  application:
    name: autoevaluacion

    jpa:
      database: postgresql
      show-sql: false

    datasource:
      plataform: postgresql
      url: jdbc:postgresql://localhost:5432/autoevaluacion
      username: postgres
      password: root
      driver-class-name: org.postgresql.Driver

  server:
    port: 8080