spring:
  application:
    name: autoevaluacion
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:postgresql://db:5432/autoevaluacion
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      platform: postgresql

server:
  port: 8080
  servlet:
    context-path: /api

frontend:
  origin: http://localhost:3000

logging:
  level:
    '[org.hibernate.sql]': DEBUG